import express, { Request, Response } from 'express';
import * as cheerio from 'cheerio';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(express.json());

// Serve static assets from public/ directory
const publicDir = path.resolve(__dirname, 'public');
if (fs.existsSync(publicDir)) {
  app.use(express.static(publicDir));
}

// In-memory feed storage and cache
interface FeedItem {
  title: string;
  url: string;
  description: string;
  publishedAt: string;
  publishedLabel?: string;
  excerpt?: string;
  imageUrl?: string;
}

interface FeedRecord {
  id: string;
  name: string;
  url: string;
  feed_token: string;
  public_url: string;
  json_public_url: string;
  created_at: string;
  updated_at: string;
}

interface StoredFeed {
  feed: FeedRecord;
  channel: {
    title: string;
    url: string;
    description: string;
  };
  items: FeedItem[];
  cachedAt: number;
}

const feedsCache = new Map<string, StoredFeed>();

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function generateToken(url: string): string {
  // Use full URL-safe base64url without truncation so it can always be statelessly decoded
  return Buffer.from(url.trim(), 'utf8').toString('base64url');
}

// Scrape website and extract items
async function scrapeUrl(targetUrl: string, customSelectors?: { items?: string; title?: string; url?: string; description?: string }): Promise<{
  channel: { title: string; url: string; description: string };
  items: FeedItem[];
}> {
  let normalized = targetUrl.trim();
  if (!/^https?:\/\//i.test(normalized)) {
    normalized = `https://${normalized}`;
  }

  const response = await fetch(normalized, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 (compatible; html2rss/1.13.0; +https://github.com/html2rss/html2rss-web)',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.9',
    },
    signal: AbortSignal.timeout(12000),
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch website (HTTP ${response.status}: ${response.statusText})`);
  }

  const html = await response.text();
  const $ = cheerio.load(html);

  // Extract channel metadata
  const channelTitle =
    $('meta[property="og:title"]').attr('content') ||
    $('title').text().trim() ||
    new URL(normalized).hostname;

  const channelDesc =
    $('meta[name="description"]').attr('content') ||
    $('meta[property="og:description"]').attr('content') ||
    `RSS feed for ${channelTitle} generated by html2rss-web`;

  const items: FeedItem[] = [];
  const seenUrls = new Set<string>();

  // Helper to resolve URL
  const resolveHref = (href?: string): string | undefined => {
    if (!href || href.startsWith('javascript:') || href.startsWith('#')) return undefined;
    try {
      return new URL(href, normalized).href;
    } catch {
      return undefined;
    }
  };

  if (customSelectors?.items) {
    // Custom selector mode
    $(customSelectors.items).each((_, el) => {
      const $el = $(el);
      const title = (customSelectors.title ? $el.find(customSelectors.title).text() : $el.text()).trim();
      const rawHref = customSelectors.url ? $el.find(customSelectors.url).attr('href') : $el.find('a').attr('href');
      const itemUrl = resolveHref(rawHref);
      const description = (customSelectors.description ? $el.find(customSelectors.description).text() : '').trim();

      if (title && itemUrl && !seenUrls.has(itemUrl)) {
        seenUrls.add(itemUrl);
        items.push({
          title,
          url: itemUrl,
          description: description || title,
          publishedAt: new Date().toISOString(),
          publishedLabel: new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }),
          excerpt: description.slice(0, 200),
        });
      }
    });
  } else {
    // Auto-source mode: smart selector discovery

    // Special site handling: Hacker News
    if (normalized.includes('news.ycombinator.com')) {
      $('.athing').each((_, el) => {
        const $el = $(el);
        const titleEl = $el.find('.titleline > a').first();
        const title = titleEl.text().trim();
        const rawHref = titleEl.attr('href');
        const itemUrl = resolveHref(rawHref);
        const subtext = $el.next('tr').find('.subtext').text().trim();

        if (title && itemUrl && !seenUrls.has(itemUrl)) {
          seenUrls.add(itemUrl);
          items.push({
            title,
            url: itemUrl,
            description: subtext || title,
            publishedAt: new Date().toISOString(),
            publishedLabel: 'Today',
            excerpt: subtext,
          });
        }
      });
    }

    // Special site handling: GitHub Trending
    if (items.length === 0 && normalized.includes('github.com/trending')) {
      $('article.Box-row').each((_, el) => {
        const $el = $(el);
        const titleEl = $el.find('h2 a').first();
        const title = titleEl.text().replace(/\s+/g, ' ').trim();
        const itemUrl = resolveHref(titleEl.attr('href'));
        const desc = $el.find('p').text().trim();

        if (title && itemUrl && !seenUrls.has(itemUrl)) {
          seenUrls.add(itemUrl);
          items.push({
            title,
            url: itemUrl,
            description: desc || title,
            publishedAt: new Date().toISOString(),
            publishedLabel: 'Today',
            excerpt: desc,
          });
        }
      });
    }

    // Generic article containers and news link extraction
    if (items.length === 0) {
      // First check for dedicated news / announcements links (common on Turkish and government/corporate sites)
      $('a[href*="/Haber/"], a[href*="/Duyuru/"], a[href*="/haber/"], a[href*="/duyuru/"], a[href*="/news/"], a[href*="/post/"]').each((_, el) => {
        if (items.length >= 25) return;
        const $el = $(el);
        let title = $el.text().replace(/\s+/g, ' ').trim();
        const rawHref = $el.attr('href');
        const itemUrl = resolveHref(rawHref);

        // If link text is "Devamı" or "Tümü", try finding title in parent or preceding heading
        if (title.toLowerCase() === 'devamı' || title.toLowerCase() === 'tümü' || title.length < 5) {
          const parentHeading = $el.closest('div, li, tr').find('h2, h3, h4, h5, .title, strong').first();
          if (parentHeading.length) {
            title = parentHeading.text().replace(/\s+/g, ' ').trim();
          }
        }

        if (title.length > 5 && itemUrl && !seenUrls.has(itemUrl)) {
          seenUrls.add(itemUrl);
          const excerpt = $el.closest('div, li, tr').find('p').first().text().replace(/\s+/g, ' ').trim() || title;
          items.push({
            title,
            url: itemUrl,
            description: excerpt,
            publishedAt: new Date().toISOString(),
            publishedLabel: 'Son Haberler',
            excerpt: excerpt.slice(0, 200),
          });
        }
      });
    }

    if (items.length === 0) {
      const containerSelectors = [
        'article',
        '.post',
        '.article',
        '.story',
        '.news-item',
        '.entry',
        '.item',
        '.c-card',
        '.card',
        '.feed-item',
        'li:has(h2 a[href])',
        'li:has(h3 a[href])',
        'div[class*="post"]',
        'div[class*="article"]',
        'div[class*="entry"]',
        'div[class*="story"]',
      ];

      for (const selector of containerSelectors) {
        if (items.length >= 10) break;
        $(selector).each((_, el) => {
          if (items.length >= 30) return;
          const $el = $(el);

          // Find title inside container
          const heading = $el.find('h1, h2, h3, h4, .title, .headline, a[class*="title"]').first();
          let title = heading.text().trim();
          let linkEl = heading.is('a') ? heading : heading.find('a').first();
          if (!linkEl.length) {
            linkEl = $el.find('a[href]').first();
          }

          if (!title) {
            title = linkEl.text().trim();
          }

          title = title.replace(/\s+/g, ' ').trim();
          const itemUrl = resolveHref(linkEl.attr('href'));

          if (title.length > 3 && itemUrl && !seenUrls.has(itemUrl)) {
            // Find description/excerpt
            const excerpt =
              $el.find('p, .summary, .description, .excerpt, .snippet').first().text().replace(/\s+/g, ' ').trim() ||
              '';

            // Find time
            const timeVal =
              $el.find('time').attr('datetime') ||
              $el.find('time').text().trim() ||
              $el.find('.date, .time, .published').text().trim();

            let pubDate = new Date().toISOString();
            let pubLabel = 'Recent';
            if (timeVal) {
              const parsed = new Date(timeVal);
              if (!isNaN(parsed.getTime())) {
                pubDate = parsed.toISOString();
                pubLabel = parsed.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
              } else {
                pubLabel = timeVal.slice(0, 24);
              }
            }

            // Find image
            const imgUrl = resolveHref($el.find('img').attr('src'));

            seenUrls.add(itemUrl);
            items.push({
              title,
              url: itemUrl,
              description: excerpt || title,
              publishedAt: pubDate,
              publishedLabel: pubLabel,
              excerpt: excerpt.slice(0, 240),
              imageUrl: imgUrl,
            });
          }
        });
      }
    }

    // Fallback: prominent links if no articles detected
    if (items.length === 0) {
      $('main a[href], #content a[href], body a[href]').each((_, el) => {
        if (items.length >= 25) return;
        const $el = $(el);
        const text = $el.text().replace(/\s+/g, ' ').trim();
        const href = resolveHref($el.attr('href'));

        if (text.length >= 15 && href && !seenUrls.has(href)) {
          // Avoid common navigation links
          const lower = text.toLowerCase();
          if (
            ['about', 'contact', 'privacy', 'terms', 'home', 'login', 'sign up', 'register', 'cookie'].some((skip) =>
              lower.includes(skip)
            )
          ) {
            return;
          }

          seenUrls.add(href);
          items.push({
            title: text,
            url: href,
            description: text,
            publishedAt: new Date().toISOString(),
            publishedLabel: 'Recent',
            excerpt: text,
          });
        }
      });
    }
  }

  return {
    channel: {
      title: channelTitle,
      url: normalized,
      description: channelDesc,
    },
    items,
  };
}

// Preconfigured Catalog Feeds
interface CatalogConfig {
  id: string;
  path: string;
  title: string;
  description: string;
  channelUrl: string;
  defaults?: Record<string, string>;
}

const CATALOG_CONFIGS: CatalogConfig[] = [
  {
    id: 'hackernews',
    path: '/hackernews.rss',
    title: 'Hacker News Frontpage',
    description: 'Top headlines and technology conversations from Hacker News.',
    channelUrl: 'https://news.ycombinator.com',
  },
  {
    id: 'github-trending',
    path: '/github-trending.rss',
    title: 'GitHub Trending Repositories',
    description: 'Trending open-source projects on GitHub today.',
    channelUrl: 'https://github.com/trending',
  },
  {
    id: 'lobsters',
    path: '/lobsters.rss',
    title: 'Lobste.rs Stories',
    description: 'Computing-focused link aggregation and discussions.',
    channelUrl: 'https://lobste.rs',
  },
  {
    id: 'devto',
    path: '/devto.rss',
    title: 'Dev.to Community Feed',
    description: 'Constructive and inclusive social network for software developers.',
    channelUrl: 'https://dev.to',
  },
  {
    id: 'techcrunch',
    path: '/techcrunch.rss',
    title: 'TechCrunch Latest',
    description: 'Startup and technology news, funding rounds, and product launches.',
    channelUrl: 'https://techcrunch.com',
  },
  {
    id: 'slashdot',
    path: '/slashdot.rss',
    title: 'Slashdot: News for Nerds',
    description: 'Timely tech news, open-source updates, and discussions.',
    channelUrl: 'https://slashdot.org',
  },
  {
    id: 'chip-testberichte',
    path: '/chip-testberichte.rss',
    title: 'CHIP Testberichte',
    description: 'Aktuelle Produkttests und Kaufberatung von CHIP.',
    channelUrl: 'https://www.chip.de/testberichte',
  },
  {
    id: 'example',
    path: '/example.rss',
    title: "html2rss-web Commits",
    description: "Latest commits on html2rss-web's main branch.",
    channelUrl: 'https://github.com/html2rss/html2rss-web/commits/main',
  },
];

// Helper to get or scrape a feed
async function getOrScrapeFeed(url: string, origin: string): Promise<StoredFeed> {
  const token = generateToken(url);
  const existing = feedsCache.get(token);
  const now = Date.now();

  // Cache for 10 minutes
  if (existing && now - existing.cachedAt < 10 * 60 * 1000) {
    return existing;
  }

  const scraped = await scrapeUrl(url);
  const feedRecord: FeedRecord = {
    id: token,
    name: scraped.channel.title || url,
    url: url,
    feed_token: token,
    public_url: `/feeds/${token}.rss`,
    json_public_url: `/feeds/${token}.json`,
    created_at: existing ? existing.feed.created_at : new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const stored: StoredFeed = {
    feed: feedRecord,
    channel: scraped.channel,
    items: scraped.items,
    cachedAt: now,
  };

  feedsCache.set(token, stored);
  return stored;
}

// XML RSS 2.0 Renderer
function renderRssXml(feed: StoredFeed, origin: string): string {
  const selfUrl = `${origin}/feeds/${feed.feed.feed_token}.rss`;
  const itemsXml = feed.items
    .map((item) => {
      const pubDate = item.publishedAt ? new Date(item.publishedAt).toUTCString() : new Date().toUTCString();
      const enclosure = item.imageUrl
        ? `\n      <enclosure url="${escapeXml(item.imageUrl)}" type="image/jpeg" length="0" />`
        : '';
      return `    <item>
      <title>${escapeXml(item.title)}</title>
      <link>${escapeXml(item.url)}</link>
      <guid isPermaLink="true">${escapeXml(item.url)}</guid>
      <pubDate>${pubDate}</pubDate>
      <description><![CDATA[${item.description || item.title}]]></description>${enclosure}
    </item>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/rss.xsl"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${escapeXml(feed.channel.title || 'Feed')}</title>
    <link>${escapeXml(feed.channel.url)}</link>
    <description>${escapeXml(feed.channel.description || 'Generated by html2rss-web')}</description>
    <atom:link href="${escapeXml(selfUrl)}" rel="self" type="application/rss+xml"/>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <generator>html2rss-web (https://github.com/html2rss/html2rss-web)</generator>
${itemsXml}
  </channel>
</rss>`;
}

// JSON Feed 1.1 Renderer
function renderJsonFeed(feed: StoredFeed, origin: string) {
  return {
    version: 'https://jsonfeed.org/version/1.1',
    title: feed.channel.title || feed.feed.name,
    home_page_url: feed.channel.url,
    feed_url: `${origin}/feeds/${feed.feed.feed_token}.json`,
    description: feed.channel.description,
    items: feed.items.map((item) => ({
      id: item.url,
      url: item.url,
      title: item.title,
      content_html: `<p>${escapeXml(item.description || '')}</p>`,
      summary: item.description,
      date_published: item.publishedAt,
      ...(item.imageUrl ? { image: item.imageUrl } : {}),
    })),
  };
}

// ----------------------------------------------------
// API V1 Routes
// ----------------------------------------------------

// GET /api/v1 - API metadata
app.get('/api/v1', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      api: {
        name: 'html2rss-web',
        description: 'Turn almost any website into an RSS or JSON feed',
        openapi_url: '/openapi.yaml',
      },
      instance: {
        catalog: {
          enabled: true,
          url: '/api/v1/configs',
        },
        feed_creation: {
          enabled: true,
          access_token_required: false,
        },
      },
    },
  });
});

// GET /api/v1/configs - Catalog configs
app.get('/api/v1/configs', (req: Request, res: Response) => {
  const configs = CATALOG_CONFIGS.map((cfg) => ({
    id: cfg.id,
    path: cfg.path,
    channel: { url: cfg.channelUrl },
    directory: {
      title: cfg.title,
      summary: cfg.description,
    },
    parameters: { defaults: cfg.defaults || {} },
    last_result: {
      state: 'ok',
      at: new Date().toISOString(),
    },
  }));

  res.json({
    success: true,
    data: { configs },
    meta: {
      total: configs.length,
      catalog_version: 2,
      starters: ['hackernews', 'github-trending', 'chip-testberichte'],
    },
  });
});

// GET /api/v1/strategies - Extraction strategies
app.get('/api/v1/strategies', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      strategies: [
        {
          id: 'auto_source',
          name: 'Auto Source',
          display_name: 'Automatic Page Extraction',
        },
        {
          id: 'articles',
          name: 'Articles',
          display_name: 'News & Blog Articles',
        },
        {
          id: 'custom_selectors',
          name: 'Custom Selectors',
          display_name: 'CSS Selector Extraction',
        },
      ],
    },
    meta: { total: 3 },
  });
});

// Health checks
app.get('/api/v1/health', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      health: {
        status: 'healthy',
        environment: process.env.NODE_ENV || 'production',
        timestamp: new Date().toISOString(),
        uptime: process.uptime(),
        checks: {
          scraper: 'ok',
          cache: 'ok',
        },
      },
    },
  });
});

app.get('/api/v1/health/live', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      health: {
        status: 'live',
        timestamp: new Date().toISOString(),
      },
    },
  });
});

app.get('/api/v1/health/ready', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      health: {
        status: 'ready',
        environment: process.env.NODE_ENV || 'production',
        timestamp: new Date().toISOString(),
        uptime: process.uptime(),
        checks: {},
      },
    },
  });
});

// POST /api/v1/feeds - Create feed
app.post('/api/v1/feeds', async (req: Request, res: Response) => {
  try {
    const { url, selectors } = req.body;
    if (!url || typeof url !== 'string' || !url.trim()) {
      return res.status(400).json({
        success: false,
        error: {
          kind: 'input',
          code: 'INVALID_INPUT',
          message: 'URL is required.',
          retryable: false,
          next_action: 'correct_input',
          retry_action: 'none',
        },
      });
    }

    const host = req.get('host') || 'localhost:3000';
    const protocol = req.protocol === 'https' || req.get('x-forwarded-proto') === 'https' ? 'https' : 'http';
    const origin = `${protocol}://${host}`;

    let scrapedFeed: StoredFeed;
    if (selectors && typeof selectors === 'object') {
      const scraped = await scrapeUrl(url, selectors);
      const token = generateToken(url);
      scrapedFeed = {
        feed: {
          id: token,
          name: scraped.channel.title || url,
          url,
          feed_token: token,
          public_url: `/feeds/${token}.rss`,
          json_public_url: `/feeds/${token}.json`,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        channel: scraped.channel,
        items: scraped.items,
        cachedAt: Date.now(),
      };
      feedsCache.set(token, scrapedFeed);
    } else {
      scrapedFeed = await getOrScrapeFeed(url, origin);
    }

    if (scrapedFeed.items.length === 0) {
      return res.status(422).json({
        success: false,
        error: {
          kind: 'input',
          code: 'EMPTY_EXTRACT',
          message: "Couldn't detect any feed items on this webpage. Check the URL or try another page.",
          retryable: true,
          next_action: 'retry',
          retry_action: 'primary',
        },
      });
    }

    return res.json({
      success: true,
      data: {
        feed: scrapedFeed.feed,
        preview: {
          channel: scrapedFeed.channel,
          items: scrapedFeed.items.slice(0, 10),
        },
      },
    });
  } catch (error: any) {
    console.error('Feed creation error:', error);
    return res.status(500).json({
      success: false,
      error: {
        kind: 'server',
        code: 'CREATION_FAILED',
        message: error.message || 'Unable to create feed from this URL.',
        retryable: true,
        next_action: 'retry',
        retry_action: 'primary',
      },
    });
  }
});

// GET /api/v1/feeds/:token - Feed metadata & preview
app.get('/api/v1/feeds/:token', async (req: Request, res: Response) => {
  const token = req.params.token.replace(/\.(rss|xml|json)$/, '');
  const stored = feedsCache.get(token);
  if (!stored) {
    return res.status(404).json({
      success: false,
      error: {
        kind: 'input',
        code: 'NOT_FOUND',
        message: 'Feed not found.',
        retryable: false,
        next_action: 'correct_input',
        retry_action: 'none',
      },
    });
  }

  res.json({
    success: true,
    data: {
      feed: stored.feed,
      preview: {
        channel: stored.channel,
        items: stored.items.slice(0, 10),
      },
    },
  });
});

// ----------------------------------------------------
// Feed Rendering Routes: /feeds/:token.rss and /feeds/:token.json
// ----------------------------------------------------

// Direct /feed endpoint by URL: /feed?url=https://...
app.get('/feed', async (req: Request, res: Response) => {
  const targetUrl = req.query.url as string;
  if (!targetUrl || typeof targetUrl !== 'string') {
    return res.status(400).send('Query parameter ?url= is required');
  }

  const format = (req.query.format as string) || (req.get('accept')?.includes('json') ? 'json' : 'rss');
  const host = req.get('host') || 'localhost:3000';
  const protocol = req.protocol === 'https' || req.get('x-forwarded-proto') === 'https' ? 'https' : 'http';
  const origin = `${protocol}://${host}`;

  try {
    const stored = await getOrScrapeFeed(targetUrl, origin);
    if (format === 'json') {
      res.setHeader('Content-Type', 'application/feed+json; charset=utf-8');
      return res.json(renderJsonFeed(stored, origin));
    } else {
      res.setHeader('Content-Type', 'application/rss+xml; charset=utf-8');
      return res.send(renderRssXml(stored, origin));
    }
  } catch (error: any) {
    return res.status(500).send(`Error generating feed: ${error.message}`);
  }
});

app.get('/feeds/:token', async (req: Request, res: Response) => {
  const rawParam = req.params.token;
  const isJson = rawParam.endsWith('.json') || (req.get('accept') && req.get('accept')?.includes('json'));
  let token = rawParam.replace(/\.(rss|xml|json)$/, '');

  const host = req.get('host') || 'localhost:3000';
  const protocol = req.protocol === 'https' || req.get('x-forwarded-proto') === 'https' ? 'https' : 'http';
  const origin = `${protocol}://${host}`;

  // Handle aliases and legacy/truncated tokens
  if (token === 'aHR0cHM6Ly93d3cudGFyaW1vcm1hbi5n' || token === 'tarimorman') {
    token = generateToken('https://www.tarimorman.gov.tr');
  }

  let stored = feedsCache.get(token);

  // If not found in cache, check if token decodes to a valid URL
  if (!stored) {
    try {
      let decodedUrl = Buffer.from(token, 'base64url').toString('utf8');
      if (decodedUrl.startsWith('https://www.tarimorman.g')) {
        decodedUrl = 'https://www.tarimorman.gov.tr';
      }
      if (/^https?:\/\//i.test(decodedUrl)) {
        stored = await getOrScrapeFeed(decodedUrl, origin);
      }
    } catch {
      // not a base64url
    }
  }

  if (!stored) {
    return res.status(404).send('Feed not found');
  }

  if (isJson) {
    res.setHeader('Content-Type', 'application/feed+json; charset=utf-8');
    return res.json(renderJsonFeed(stored, origin));
  } else {
    res.setHeader('Content-Type', 'application/rss+xml; charset=utf-8');
    return res.send(renderRssXml(stored, origin));
  }
});

// Catalog named feed endpoints (e.g., /hackernews.rss, /github-trending.rss)
app.get('/:catalogName', async (req: Request, res: Response, next) => {
  const param = req.params.catalogName;
  if (!param.endsWith('.rss') && !param.endsWith('.xml') && !param.endsWith('.json')) {
    return next();
  }

  const isJson = param.endsWith('.json');
  const baseName = param.replace(/\.(rss|xml|json)$/, '');
  const catalogEntry = CATALOG_CONFIGS.find((cfg) => cfg.id === baseName);

  if (!catalogEntry) {
    return next();
  }

  try {
    const host = req.get('host') || 'localhost:3000';
    const protocol = req.protocol === 'https' || req.get('x-forwarded-proto') === 'https' ? 'https' : 'http';
    const origin = `${protocol}://${host}`;
    const stored = await getOrScrapeFeed(catalogEntry.channelUrl, origin);

    if (isJson) {
      res.setHeader('Content-Type', 'application/feed+json; charset=utf-8');
      return res.json(renderJsonFeed(stored, origin));
    } else {
      res.setHeader('Content-Type', 'application/rss+xml; charset=utf-8');
      return res.send(renderRssXml(stored, origin));
    }
  } catch (error: any) {
    return res.status(500).send(`Error generating feed: ${error.message}`);
  }
});

// ----------------------------------------------------
// Frontend Mounting (Vite in Dev / Static in Prod)
// ----------------------------------------------------
const distPath = path.resolve(__dirname, 'dist');
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath));
  app.get('*', (req: Request, res: Response, next) => {
    if (req.path.startsWith('/api') || req.path.startsWith('/rss') || req.path.startsWith('/json') || req.path.startsWith('/feed')) {
      return next();
    }
    res.sendFile(path.resolve(distPath, 'index.html'));
  });
}

export { app };
export default app;

if (!process.env.VERCEL) {
  async function startServer() {
    const PORT = Number(process.env.PORT) || 3000;

    if (process.env.NODE_ENV !== 'production' && !fs.existsSync(distPath)) {
      try {
        const { createServer: createViteServer } = await import('vite');
        const vite = await createViteServer({
          server: {
            middlewareMode: true,
            host: '0.0.0.0',
            port: PORT,
          },
          appType: 'spa',
        });
        app.use(vite.middlewares);
      } catch (e) {
        console.warn('Vite dev middleware omitted:', e);
      }
    }

    app.listen(PORT, '0.0.0.0', () => {
      console.log(`html2rss-web server running at http://localhost:${PORT}`);
    });
  }

  startServer().catch((err) => {
    console.error('Failed to start server:', err);
  });
}

